; This file was auto-generated by drush make
core = 7.x

api = 2

projects[admin_menu][version] = "3.0-rc4"
projects[coder][version] = "2.0"
projects[ctools][version] = "1.3"
projects[devel][version] = "1.3"
projects[features][version] = "2.0-rc5"
projects[grammar_parser][version] = "1.2"
projects[schema][version] = "1.0-rc1"
projects[XHProf][version] = "1.0-beta2"

